/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.cassandra.tools.schemadesigner.migration;

import java.util.stream.Collectors;

/**
 * Generates migration code in various languages.
 */
public class CodeGenerator
{
    public enum Language
    {
        JAVA, PYTHON, CQL_SCRIPT, BASH
    }

    public String generate(MigrationPlan plan, Language language)
    {
        switch (language)
        {
            case JAVA:
                return generateJava(plan);
            case PYTHON:
                return generatePython(plan);
            case CQL_SCRIPT:
                return generateCQL(plan);
            case BASH:
                return generateBash(plan);
            default:
                throw new IllegalArgumentException("Unsupported language: " + language);
        }
    }

    private String generateJava(MigrationPlan plan)
    {
        StringBuilder code = new StringBuilder();

        code.append("import com.datastax.driver.core.*;\n\n");
        code.append("public class SchemaMigration {\n");
        code.append("    private final Session session;\n\n");
        code.append("    public SchemaMigration(Session session) {\n");
        code.append("        this.session = session;\n");
        code.append("    }\n\n");

        code.append("    public void migrate() throws Exception {\n");
        for (MigrationPhase phase : plan.getPhases())
        {
            code.append("        // Phase: ").append(phase.getName()).append("\n");
            for (MigrationStep step : phase.getSteps())
            {
                code.append("        session.execute(\"").append(escapeCQL(step.getCql())).append("\");\n");
            }
            code.append("\n");
        }
        code.append("    }\n");

        code.append("}\n");

        return code.toString();
    }

    private String generatePython(MigrationPlan plan)
    {
        StringBuilder code = new StringBuilder();

        code.append("from cassandra.cluster import Cluster\n\n");
        code.append("def migrate(session):\n");
        code.append("    \"\"\"Execute schema migration\"\"\"\n");

        for (MigrationPhase phase : plan.getPhases())
        {
            code.append("    # Phase: ").append(phase.getName()).append("\n");
            for (MigrationStep step : phase.getSteps())
            {
                code.append("    session.execute(\"\"\"").append(step.getCql()).append("\"\"\")\n");
            }
            code.append("\n");
        }

        code.append("\nif __name__ == '__main__':\n");
        code.append("    cluster = Cluster(['localhost'])\n");
        code.append("    session = cluster.connect()\n");
        code.append("    migrate(session)\n");
        code.append("    cluster.shutdown()\n");

        return code.toString();
    }

    private String generateCQL(MigrationPlan plan)
    {
        StringBuilder code = new StringBuilder();

        code.append("-- Schema Migration Script\n");
        code.append("-- Generated by Cassandra Schema Designer\n\n");

        for (MigrationPhase phase : plan.getPhases())
        {
            code.append("-- Phase: ").append(phase.getName()).append("\n");
            code.append("-- ").append(phase.getDescription()).append("\n\n");

            for (MigrationStep step : phase.getSteps())
            {
                code.append("-- ").append(step.getDescription()).append("\n");
                code.append(step.getCql()).append(";\n\n");
            }
        }

        return code.toString();
    }

    private String generateBash(MigrationPlan plan)
    {
        StringBuilder code = new StringBuilder();

        code.append("#!/bin/bash\n");
        code.append("# Schema Migration Script\n");
        code.append("# Generated by Cassandra Schema Designer\n\n");

        code.append("CQLSH=\"cqlsh\"\n");
        code.append("CONTACT_POINT=\"${1:-localhost}\"\n\n");

        code.append("echo \"Starting migration...\"\n\n");

        int phaseNum = 1;
        for (MigrationPhase phase : plan.getPhases())
        {
            code.append("# Phase ").append(phaseNum++).append(": ").append(phase.getName()).append("\n");
            code.append("echo \"Phase: ").append(phase.getName()).append("\"\n");

            for (MigrationStep step : phase.getSteps())
            {
                code.append("$CQLSH $CONTACT_POINT -e \"").append(escapeBash(step.getCql())).append("\"\n");
                code.append("if [ $? -ne 0 ]; then\n");
                code.append("    echo \"Error in step: ").append(step.getDescription()).append("\"\n");
                code.append("    exit 1\n");
                code.append("fi\n");
            }
            code.append("\n");
        }

        code.append("echo \"Migration completed successfully!\"\n");

        return code.toString();
    }

    private String escapeCQL(String cql)
    {
        return cql.replace("\"", "\\\"");
    }

    private String escapeBash(String str)
    {
        return str.replace("\"", "\\\"").replace("$", "\\$");
    }
}
